# Generated by Django 5.1 on 2024-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новое мероприятие', max_length=200, verbose_name='Название')),
                ('print_title', models.TextField(verbose_name='Название для печати')),
                ('description', models.TextField(verbose_name='Описание')),
                ('from_date', models.DateField(verbose_name='Дата начала')),
                ('to_date', models.DateField(verbose_name='Дата окончания')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания мероприятия')),
            ],
        ),
    ]
