# Generated by Django 5.1 on 2024-08-30 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_events_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='events',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
